spring:
  application:
    name: affable-bean-backend

  datasource:
    url: jdbc:mysql://localhost:3306/affable_bootcamp6
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
